import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
import ChatWidget from "../components/ChatWidget";
import Footer from "../components/Footer";
import { ensurePresetIndexes } from "../lib/mongodb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhotoGen",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Warm DB indexes / connection in the background during initial render.
  // We don't await aggressively to avoid slowing SSR; this kicks off the promise.
  try {
    ensurePresetIndexes().catch(() => {});
  } catch {}

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/gen.svg" />
  {/* Preconnect to Cloudinary to improve image fetch latency */}
  <link rel="preconnect" href="https://res.cloudinary.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
  <Nav />
  {children}
  <ChatWidget />
  <Footer />
      </body>
    </html>
  );
}
